language: python
python:
    - "3.6"

install:
    - pip install -r requirements/base.txt
    - pip install psycopg2 --quiet

services:
    - postgresql

script:
    python manage.py test

env:
    - SECRET_KEY=cem@+@8%j)_l=__&3(e41hh4ose1x-7-aaq+i&3d3l!2h2y84_
