language: python
python:
    - "3.6"

install:
    - pip install -r requirements/base.txt
    - pip install psycopg2-binary --quiet

services:
    - postgresql

before_script:
  - psql -c "CREATE DATABASE eyobofficial_website;" -U postgres

script:
    python manage.py test
